### PR TITLE
Adding case studi of Prettier Code Formatter for VSCode

### PR DESCRIPTION
**Pull request by Kobraz**

### CODE REVIEW

**Comment by EkaterinaNattrass** [comment]
Hello again,Roar. The contents looked really good, very straight to the point and well structured. The only thing I would probably change is this sentnce 'Here, I will take a closer look at the differences between Prettier and ESLint.' I remember Oliver mentioning not to use first person in Academic writing:) Maybe something like 'Let's take a closer look'?

**Comment by Kobraz** [comment]
Thank you very much. I appreciate it.

fre. 16. feb. 2024, 20:35 skrev EkaNat ***@***.***>:

**Comment by Kobraz** [comment]
I did make changes based on the feedback from @EkaterinaNattrass

**Review by sulenchy — APPROVED** [review]
Good job! @Kobraz 
You have chosen a really nice topic, and it is fully covered in line with the requirements of the CA. However, its comprehension could be improved with visual aids. Adding related images to an article helps users understand better.

**Pull request merged**
