### PR TITLE
Docker case study

### PR DESCRIPTION
**Pull request by EkaterinaNattrass**
Development platforms course assignment with a case study of Docker and containerization in generall

### CODE REVIEW

**Review by sulenchy — COMMENTED** [review]
@EkaterinaNattrass Good write up I must say. However, the demonstration is missing. In the CA brief, part of what want to see is the demonstration of the use of the tool(Docker).That is the only thing missing. Can you fix that?

**Comment by EkaterinaNattrass** [comment]
Thank you for your feedback, Abi! I have added Docker demonstration with basic commands based on your review.

**Comment by Kobraz** [comment]
Hi. I learned a lot about Docker reading your case study, well done. Nothing to correct from me, but I wonder if @sulenchy can tell if the references have to be [Harvard style ](https://i.ntnu.no/academic-writing/harvard) in these documents too.

I dont know if its required, but I have set mine up like this:
image

Well done.

If you have the opportunity to take a look at my case study, I would greatly appreciate feedback.

**Comment by EkaterinaNattrass** [comment]
Hi, Roar! Thanks for your review. Abi didn't say anything about my links, and I was using the provided template, so hope it will be fine. Will be happy to read your case study. Could you send me a PR link?

**Comment by Kobraz** [comment]
Yes, here is my link:
https://github.com/Kobraz/development-platforms/blob/prettier-case-study/src/content/docs/devtools/IDE/prettier-case-study.md

fre. 16. feb. 2024, 16:51 skrev EkaNat ***@***.***>:

**Review by Fermain — APPROVED** [review]
This is a really high quality and engaging case study that captures the interest of the reader and provides ample detail about what Docker is, how it works and how we can use it practically.

**Pull request merged**
