### PR TITLE
Captcha case study

### PR DESCRIPTION
**Pull request by idanguyen**
Look into bot prevention with CAPTCHA

### CODE REVIEW

**Review by sulenchy — CHANGES_REQUESTED** [review]
Great topic, and good job explaining the concepts and ideas around CAPTCHA. However, you need to go further by demonstrating the integration of CAPTCHA into a website. @idanguyen

**Comment by sulenchy** [comment]
You can demonstrate how to add Recaptcha to a website. See https://www.google.com/recaptcha/about/

**Comment by idanguyen** [comment]
Added implemation

**Review by sulenchy — APPROVED** [review]
Looks good to me now

**Pull request merged**
