### PR TITLE
case study of sheCodes

### PR DESCRIPTION
**Pull request by OlgaGoryszewska**
This document presents a comprehensive case study of SheCodes, a platform dedicated to empowering women by teaching them coding skills. SheCodes was specifically created to address the gender disparity in the technology sector by providing an inclusive, supportive environment for women to develop coding competencies.

### CODE REVIEW

**Comment by Teitrheim** [comment]
This looks great!! Did not know of sheCodes before this case study.

**Review by jaaneh — CHANGES_REQUESTED** [review]
- Can you maybe tone down the use of bold in tables and lists a tad?
- Please rename your case-study file to include your github username (`shecodes-case-study-olgagoryszewska`).

Overall, the case study is well-structured and provides a good overview of SheCodes.

**Review by OlgaGoryszewska — COMMENTED** [review]
thank you for feedback

**Review by OlgaGoryszewska — COMMENTED** [review]
i have changed a name of the file

**Comment by OlgaGoryszewska** [comment]
final changes to the case study

**Review by OlgaGoryszewska — COMMENTED** [review]
added changes from review

**Comment by OlgaGoryszewska** [comment]
Final changes

**Review by sulenchy — CHANGES_REQUESTED** [review]
@OlgaGoryszewska Thanks for the effort you have put into this research. However, this topic does not meet the major criterion of the CA. It is specifically mentioned in the brief that you should write about a development platform product. SheCode is a workshop for women in tech and not a product per say. 

The goal of this CA is `to demonstrate the ability to research development platform product offerings, form opinions and relate this research to others via a written or video case study`

**Comment by Fermain** [comment]
> @OlgaGoryszewska Thanks for the effort you have put into this research. However, this topic does not meet the major criterion of the CA. It is specifically mentioned in the brief that you should write about a development platform product. SheCode is a workshop for women in tech and not a product per say.
> 
> The goal of this CA is `to demonstrate the ability to research development platform product offerings, form opinions and relate this research to others via a written or video case study`

As discussed, I gave the green light for this case study although it does not fit the brief perfectly. My judgement was that students will benefit from learning about this offering and the quality of the writing is high.

**Review by sulenchy — APPROVED** [review]
Thanks for the clarification @Fermain. 

@OlgaGoryszewska The issue surrounding the topic has been resolved. Every aspect of the write-up looks good to me. The tone and the arrangement are okay. However, you have two files containing the same content. You need to remove one.

**Comment by sulenchy** [comment]
Also, your branch is out of date with the base branch. You need to merge latest changes from the main branch to your branch and push again. Else this PR wont be merge. 

@OlgaGoryszewska

**Comment by sulenchy** [comment]
@jaaneh This looks to me now. You can merge if you are cool with it.

**Comment by jaaneh** [comment]
There's 2 case study files here, please remove the one without your GitHub name in the name.  @OlgaGoryszewska 
We can merge it once that's completed @sulenchy

**Review by OlgaGoryszewska — COMMENTED** [review]
done

**Review by jaaneh — APPROVED** [review]
Thank you!

Will merge this and it will be live at https://library.noroff.dev/. Please note that it'll be findable via search only until we enable it for the sidebar.

Great job :-)

**Comment by OlgaGoryszewska** [comment]
Thank you for your response

**Pull request merged**
